### ISSUE TITLE
Charts not working when timeframe is over 3,5 years

### ISSUE THREAD

**Issue by nowaks381edu** [RCRalph/SelfAccounting#188]
Nie pokazuje że przekroczono zakres, poprostu chart się nie pokazuje

**Comment by RCRalph** [comment]
Example?

**Comment by nowaks381edu** [comment]
Balance history
01.01.2021->26.06.2024 works 
01.01.2021->27.06.2024 doesnt

**Comment by RCRalph** [comment]
Could you check if some error is appearing in the browser console?
